# LICENSE
# This file is part of TilauScope, a fork of Artisan Roaster Scope.
# TilauScope is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version. It is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
# for more details. You should have received a copy of the GNU Affero General
# Public License along with this program. If not, see
# <https://www.gnu.org/licenses/>.

# GENERATED by tools/gen_artisan_device_defaults.py — do not edit by hand.
# Source: src/artisanlib/devices.py, DeviceAssignmentDlg.okEvent.

"""What choosing a meter or adding an extra device does in Artisan, as data.

``METER_BRANCHES`` maps a meter name to ``(device id, serial settings, only on
change)``; the serial settings are written only when the device actually changes
if the last flag is set, exactly as Artisan's chain does. ``SPECIAL_METERS``
names the branches that do more than that — ``artisan_mirror.py`` replays the
rest. The two ``EXTRA_*`` tables are Artisan's serial defaults per extra device.
"""

from __future__ import annotations

from typing import Final

MeterBranch = tuple[int, dict[str, int | float | str], bool]


METER_BRANCHES: Final[dict[str, MeterBranch]] = {
    'Omega HH806AU': (1, {'baudrate': 19200, 'bytesize': 8, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'Omega HH506RA': (2, {'baudrate': 2400, 'bytesize': 7, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 309': (3, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 306': (4, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 305': (5, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 304': (6, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 303': (7, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 302': (8, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 301': (9, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'CENTER 300': (10, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'VOLTCRAFT K204': (11, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'VOLTCRAFT K202': (12, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'VOLTCRAFT 300K': (13, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.5}, True),
    'VOLTCRAFT 302KJ': (14, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'EXTECH 421509': (15, {'baudrate': 2400, 'bytesize': 7, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'Omega HH802U': (16, {'baudrate': 19200, 'bytesize': 8, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'Omega HH309': (17, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'NONE': (18, {}, False),
    'TE VA18B': (20, {'baudrate': 2400, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 1.0}, True),
    'Omega HHM28[6]': (23, {'baudrate': 2400, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 1.0}, True),
    'MODBUS': (29, {'baudrate': 115200, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.6}, True),
    'VOLTCRAFT K201': (30, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Amprobe TMD-56': (31, {'baudrate': 19200, 'bytesize': 8, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'Phidget 1048 4xTC 01': (34, {}, False),
    'Phidget 1046 4xRTD 01': (37, {}, False),
    'Mastech MS6514': (39, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Phidget IO 01': (40, {}, False),
    'Yocto Thermocouple': (45, {}, False),
    'Yocto PT100': (46, {}, False),
    'Phidget 1045 IR': (47, {}, False),
    'DUMMY': (50, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.5}, True),
    'Phidget 1051 1xTC 01': (52, {}, False),
    'Hottop BT/ET': (53, {'baudrate': 115200, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Omega HH806W': (55, {'baudrate': 38400, 'bytesize': 8, 'parity': 'E', 'stopbits': 1, 'timeout': 0.7}, True),
    'Apollo DT301': (56, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'EXTECH 755': (57, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Phidget TMP1101 4xTC 01': (58, {}, False),
    'Phidget TMP1100 1xTC': (61, {}, False),
    'Phidget 1011 IO 01': (62, {}, False),
    'Phidget HUB IO 01': (63, {}, False),
    'VOLTCRAFT PL-125-T2': (67, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Phidget TMP1200 1xRTD A': (68, {}, False),
    'Phidget IO Digital 01': (69, {}, False),
    'Phidget 1011 IO Digital 01': (73, {}, False),
    'Phidget HUB IO Digital 01': (74, {}, False),
    'VOLTCRAFT PL-125-T4': (77, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'S7': (79, {}, False),
    'Aillio Bullet R1 BT/DT': (83, {}, False),
    'Probat Middleware': (92, {}, False),
    'Phidget DAQ1400 Current': (95, {}, False),
    'Phidget DAQ1400 Frequency': (96, {}, False),
    'Phidget DAQ1400 Digital': (97, {}, False),
    'Phidget DAQ1400 Voltage': (98, {}, False),
    'Aillio Bullet R1 IBTS/DT': (99, {}, False),
    'Yocto IR': (100, {}, False),
    'Behmor BT/CT': (101, {'baudrate': 57600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'VICTOR 86B': (103, {'baudrate': 2400, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Phidget HUB IO 0': (106, {}, False),
    'Phidget HUB IO Digital 0': (107, {}, False),
    'Yocto 4-20mA Rx': (108, {}, False),
    'WebSocket': (111, {}, False),
    'HB BT/ET': (115, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.8}, True),
    'Yocto 0-10V Rx': (120, {}, False),
    'Yocto milliVolt Rx': (121, {}, False),
    'Yocto Serial': (122, {}, False),
    'Phidget VCP1000': (123, {}, False),
    'Phidget VCP1001': (124, {}, False),
    'Phidget VCP1002': (125, {}, False),
    'ARC BT/ET': (126, {'baudrate': 115200, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.4}, True),
    'Yocto Power': (129, {}, False),
    'Yocto Energy': (130, {}, False),
    'Yocto Voltage': (131, {}, False),
    'Yocto Current': (132, {}, False),
    'Yocto Sensor': (133, {}, False),
    'Santoker BT/ET': (134, {}, False),
    'Phidget DAQ1500': (137, {}, False),
    'Kaleido BT/ET': (138, {}, False),
    'IKAWA': (142, {}, False),
    'Phidget DAQ1000 01': (146, {}, False),
    'Phidget DAQ1200 01': (152, {}, False),
    'Phidget DAQ1300 01': (154, {}, False),
    'Phidget DAQ1301 01': (156, {}, False),
    'Digi-Sense 20250-07': (17, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Extech 42570': (17, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Mugma BT/ET': (164, {}, False),
    'Phidget TMP1202 1xRTD A': (168, {}, False),
    'ColorTrack Serial': (170, {}, False),
    'Santoker R BT/ET': (171, {}, False),
    'ColorTrack BT': (174, {}, False),
    'Thermoworks BlueDOT': (175, {}, False),
    'Aillio Bullet R2': (176, {}, False),
    'TASI TA612C': (184, {'baudrate': 9600, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 0.7}, True),
    'Orbiter BT/ET': (196, {'baudrate': 115200, 'bytesize': 8, 'parity': 'N', 'stopbits': 1, 'timeout': 1.0}, False),
    'MQTT': (201, {}, False),
}

SPECIAL_METERS: Final[frozenset[str]] = frozenset({
    'IKAWA',
    'NONE',
    'Omega HH506RA',
})

EXTRA_SSETTINGS: Final[tuple[tuple[int, int, str, int, float], ...]] = (
    (9600, 8, 'O', 1, 0.5),
    (19200, 8, 'E', 1, 0.5),
    (2400, 7, 'E', 1, 1),
    (9600, 8, 'N', 1, 0.5),
    (19200, 8, 'N', 1, 0.5),
    (2400, 8, 'N', 1, 1),
    (9600, 8, 'E', 1, 0.5),
    (38400, 8, 'E', 1, 0.5),
    (115200, 8, 'N', 1, 0.4),
    (57600, 8, 'N', 1, 0.4),
)

EXTRA_DEVSSETTINGS: Final[tuple[int, ...]] = (
    0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2,
    1, 3, 0, 4, 5, 3, 6, 5, 3, 3, 6, 3, 4, 8, 3, 1,
    4, 7, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 4, 1, 1, 1,
    3, 3, 3, 3, 1, 8, 8, 7, 3, 3, 1, 1, 1, 1, 1, 1,
    1, 1, 8, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 9, 9, 5, 9, 9, 1, 1, 1, 7, 1, 1,
    1, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 8, 8,
    8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 9, 9, 9,
    9, 9, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    9, 3, 3, 3, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1,
    1, 6, 6, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
    3, 3, 3, 3, 8, 8, 8, 8, 8, 1, 1, 1, 1, 1, 1, 1,
)
