"""Machine identity and durable PID calibration evidence tests."""

from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path

import pytest

from tilauscope.pid_calibration import CalibrationAuditEvent
from tilauscope.pid_calibration_store import (
    CalibrationMachineIdentity,
    build_machine_identity,
    verify_calibration_journal,
    verify_hardware_pilot_manifest,
    write_calibration_journal,
    write_hardware_pilot_manifest,
    write_zero_qualification_evidence,
)


def _identity(**changes: object) -> CalibrationMachineIdentity:
    facts: dict[str, object] = {
        "roaster_id": "test-roaster",
        "display_name": "Test Roaster",
        "temperature_unit": "C",
        "pid_source": 1,
        "heater_slider": 2,
        "action_id": 5,
        "action_command": "HEAT:{}",
        "slider_min": 0,
        "slider_max": 100,
        "slider_factor": 1.0,
        "slider_offset": 0.0,
        "inverted": False,
    }
    facts.update(changes)
    result = build_machine_identity(**facts)  # type: ignore[arg-type]
    assert result is not None
    return result


def _event() -> CalibrationAuditEvent:
    # The canonical hash for this payload is generated by a coordinator in the
    # main protocol tests; keeping this helper local would duplicate internals.
    from tilauscope.pid_calibration import (  # noqa: PLC0415
        CalibrationLimits,
        CalibrationProtocol,
        CalibrationSample,
        LiveCalibrationCoordinator,
        evaluate_calibration_readiness,
    )
    from test_pid_calibration import _ready_facts  # noqa: PLC0415

    coordinator = LiveCalibrationCoordinator(
        CalibrationProtocol(
            CalibrationLimits(target_c=200.0, baseline_power_pct=30.0),
            current_kp=10.0,
            current_ki=0.15,
            current_kd=0.0,
        ),
        heater_slider=2,
        zero_output_qualified=True,
        request_power=lambda *_args: None,
        apply_candidate=lambda _candidate: None,
        restore_config=lambda: None,
    )
    coordinator.start(
        CalibrationSample(0.0, 200.0, 0.0),
        readiness=evaluate_calibration_readiness(_ready_facts(heater_slider=2)),
    )
    return coordinator.audit_events[0]


def test_identity_changes_with_control_path_but_does_not_expose_command() -> None:
    first = _identity(action_command="PASSWORD=one;HEAT:{}")
    second = _identity(action_command="PASSWORD=two;HEAT:{}")

    assert first.fingerprint != second.fingerprint
    assert "PASSWORD" not in first.actuator_signature


@pytest.mark.parametrize(
    ("change", "value"),
    [
        ("roaster_id", None),
        ("action_id", 0),
        ("heater_slider", 4),
        ("slider_max", 0),
        ("slider_factor", 0.0),
        ("inverted", True),
    ],
)
def test_identity_fails_closed_when_a_required_fact_is_unsafe(
    change: str, value: object
) -> None:
    facts = {
        "roaster_id": "test-roaster",
        "display_name": "Test Roaster",
        "temperature_unit": "C",
        "pid_source": 1,
        "heater_slider": 2,
        "action_id": 5,
        "action_command": "HEAT:{}",
        "slider_min": 0,
        "slider_max": 100,
        "slider_factor": 1.0,
        "slider_offset": 0.0,
        "inverted": False,
    }
    facts[change] = value
    assert build_machine_identity(**facts) is None  # type: ignore[arg-type]


def test_zero_evidence_is_atomic_machine_bound_and_not_reusable(tmp_path: Path) -> None:
    identity = _identity()
    path = write_zero_qualification_evidence(
        tmp_path, identity, qualified_at_utc="2026-08-28T12:00:00+00:00"
    )

    payload = json.loads(path.read_text(encoding="utf-8"))
    assert payload["identity_fingerprint"] == identity.fingerprint
    assert payload["reusable_authorization"] is False
    assert list(tmp_path.glob("*.tmp")) == []


def test_pilot_manifest_is_exact_intact_and_never_authorizes_heat(
    tmp_path: Path,
) -> None:
    identity = _identity()
    path = write_hardware_pilot_manifest(
        tmp_path,
        identity,
        generated_at_utc="2026-08-28T12:00:00+00:00",
    )

    payload = json.loads(path.read_text(encoding="utf-8"))
    assert payload["identity"]["actuator_signature"] == identity.actuator_signature
    assert payload["authorizes_heat"] is False
    assert verify_hardware_pilot_manifest(path)

    payload["authorizes_heat"] = True
    path.write_text(json.dumps(payload), encoding="utf-8")
    assert not verify_hardware_pilot_manifest(path)


def test_journal_export_verifies_and_detects_metadata_tampering(tmp_path: Path) -> None:
    event = _event()
    path = write_calibration_journal(
        tmp_path / "run.json",
        identity=_identity(),
        events=(event,),
        outcome="safe_stop",
        reason="test",
        created_at_utc="2026-08-28T12:00:00+00:00",
    )
    assert verify_calibration_journal(path)

    payload = json.loads(path.read_text(encoding="utf-8"))
    payload["reason"] = "rewritten"
    path.write_text(json.dumps(payload), encoding="utf-8")
    assert not verify_calibration_journal(path)


def test_journal_refuses_a_tampered_event_chain(tmp_path: Path) -> None:
    event = replace(_event(), temperature_c=199.0)
    with pytest.raises(ValueError, match="invalid calibration audit chain"):
        write_calibration_journal(
            tmp_path / "run.json",
            identity=_identity(),
            events=(event,),
            outcome="safe_stop",
            reason="test",
        )
