# LICENSE
# This file is part of TilauScope, a fork of Artisan Roaster Scope.
# TilauScope is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.

"""Offline thermal identification and read-only live shadow validation.

The model deliberately remains small and auditable::

    dT/dt = gain * (heater_pct / 100) ** exponent
            - loss * (T - ambient)

The Skywalker V2 heater is approximately quadratic, hence the fixed exponent
of two.  A candidate produced offline cannot affect control.  During later real
preheats :class:`ThermalShadowSession` replays that model from the measured
burner commands and compares its free-running temperature with the probe.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections import deque
from collections.abc import Iterable, Sequence
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import median


## TILAU ## Sidecar only: thermal state never extends or mutates Artisan ProfileData.
THERMAL_MODEL_FILENAME = "tilaupid_thermal_candidate.json"
THERMAL_MODEL_SCHEMA = 1


@dataclass(frozen=True, slots=True)
class ThermalTrace:
    """One qualified preheat trace in canonical units."""

    times_sec: tuple[float, ...]
    temperatures_c: tuple[float, ...]
    burner_pct: tuple[float, ...]
    ambient_c: float
    source: str = ""

    def is_valid(self) -> bool:
        n = len(self.times_sec)
        return (
            n >= 10
            and len(self.temperatures_c) == n
            and len(self.burner_pct) == n
            and all(math.isfinite(v) for v in self.times_sec)
            and all(math.isfinite(v) for v in self.temperatures_c)
            and all(math.isfinite(v) and 0.0 <= v <= 100.0 for v in self.burner_pct)
            and all(b > a for a, b in zip(self.times_sec, self.times_sec[1:], strict=False))
            and -10.0 < self.ambient_c < 50.0
        )


@dataclass(frozen=True, slots=True)
class ThermalModelCandidate:
    """Versioned, context-bound model generated by the offline tool."""

    machine_fingerprint: str
    control_channel: str
    heating_gain_c_per_sec: float
    cooling_coeff_per_sec: float
    response_lag_sec: float
    derivative_rmse_c_per_sec: float
    rollout_rmse_c: float
    cross_validation_rmse_c: float
    n_profiles: int
    n_samples: int
    generated_at: str
    heater_exponent: float = 2.0
    schema_version: int = THERMAL_MODEL_SCHEMA

    def is_valid(self) -> bool:
        numeric = (
            self.heating_gain_c_per_sec,
            self.cooling_coeff_per_sec,
            self.response_lag_sec,
            self.derivative_rmse_c_per_sec,
            self.rollout_rmse_c,
            self.cross_validation_rmse_c,
            self.heater_exponent,
        )
        return (
            self.schema_version == THERMAL_MODEL_SCHEMA
            and bool(self.machine_fingerprint)
            and self.control_channel in {"BT", "ET"}
            and all(math.isfinite(v) for v in numeric)
            and 0.05 <= self.heating_gain_c_per_sec <= 10.0
            and 0.00005 <= self.cooling_coeff_per_sec <= 0.05
            and 0.0 <= self.response_lag_sec <= 15.0
            and math.isclose(self.heater_exponent, 2.0)
            and self.n_profiles >= 1
            and self.n_samples >= 1
        )

    @property
    def fingerprint(self) -> str:
        payload = json.dumps(asdict(self), sort_keys=True, separators=(",", ":"))
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]

    def equilibrium_power_pct(self, target_c: float, ambient_c: float) -> float:
        """Modelled heater percentage needed to balance steady heat loss."""
        required = self.cooling_coeff_per_sec * max(0.0, target_c - ambient_c)
        ratio = required / self.heating_gain_c_per_sec
        if ratio <= 0.0:
            return 0.0
        return 100.0 * ratio ** (1.0 / self.heater_exponent)

    def to_dict(self) -> dict[str, object]:
        return asdict(self)

    @classmethod
    def from_dict(cls, value: object) -> ThermalModelCandidate:
        if not isinstance(value, dict):
            raise ValueError("thermal candidate must be a JSON object")
        try:
            candidate = cls(**value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"invalid thermal candidate: {exc}") from exc
        if not candidate.is_valid():
            raise ValueError("thermal candidate values are outside safe bounds")
        return candidate


def load_candidate(path: Path) -> ThermalModelCandidate:
    """Load and strictly validate a candidate sidecar."""
    return ThermalModelCandidate.from_dict(json.loads(path.read_text(encoding="utf-8")))


def save_candidate(path: Path, candidate: ThermalModelCandidate) -> None:
    """Atomically publish a complete offline candidate."""
    if not candidate.is_valid():
        raise ValueError("refusing to save an invalid thermal candidate")
    temporary = path.with_suffix(f"{path.suffix}.tmp")
    temporary.write_text(
        json.dumps(candidate.to_dict(), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def _power_at(trace: ThermalTrace, at_sec: float) -> float:
    """Zero-order hold, matching the physical command between logged changes."""
    times = trace.times_sec
    values = trace.burner_pct
    lo, hi = 0, len(times)
    while lo < hi:
        mid = (lo + hi) // 2
        if times[mid] <= at_sec:
            lo = mid + 1
        else:
            hi = mid
    return values[max(0, lo - 1)]


def _fit_linear(rows: Sequence[tuple[float, float, float]]) -> tuple[float, float]:
    """Solve y = gain*u - loss*deltaT without a non-physical intercept."""
    a = sum(u * u for u, _loss_term, _y in rows)
    b = sum(u * loss_term for u, loss_term, _y in rows)
    c = sum(loss_term * loss_term for _u, loss_term, _y in rows)
    d = sum(u * y for u, _loss_term, y in rows)
    e = sum(loss_term * y for _u, loss_term, y in rows)
    determinant = a * c - b * b
    if abs(determinant) < 1e-12:
        raise ValueError("insufficient heater/temperature excitation")
    gain = (d * c - b * e) / determinant
    loss = (a * e - b * d) / determinant
    return gain, loss


def _identification_rows(
    traces: Sequence[ThermalTrace],
    lag_sec: float,
    derivative_window: int = 5,
) -> list[tuple[float, float, float]]:
    rows: list[tuple[float, float, float]] = []
    for trace in traces:
        n = len(trace.times_sec)
        for i in range(n - derivative_window):
            j = i + derivative_window
            dt = trace.times_sec[j] - trace.times_sec[i]
            if not 2.0 <= dt <= 12.0:
                continue
            y = (trace.temperatures_c[j] - trace.temperatures_c[i]) / dt
            if not -1.0 <= y <= 2.0:  # -60..120 °C/min: reject probe glitches
                continue
            midpoint = (trace.times_sec[i] + trace.times_sec[j]) / 2.0
            power = _power_at(trace, midpoint - lag_sec)
            u = (power / 100.0) ** 2.0
            temp = (trace.temperatures_c[i] + trace.temperatures_c[j]) / 2.0
            rows.append((u, -(temp - trace.ambient_c), y))
    return rows


def _robust_fit(rows: list[tuple[float, float, float]]) -> tuple[float, float, float, int]:
    if len(rows) < 60:
        raise ValueError("not enough qualified thermal samples")
    working = rows
    for _ in range(2):
        gain, loss = _fit_linear(working)
        residuals = [y - (gain * u + loss * lt) for u, lt, y in working]
        centre = median(residuals)
        mad = median(abs(r - centre) for r in residuals)
        cutoff = max(0.02, 4.0 * 1.4826 * mad)
        filtered = [row for row, residual in zip(working, residuals, strict=True)
                    if abs(residual - centre) <= cutoff]
        if len(filtered) < 60 or len(filtered) == len(working):
            break
        working = filtered
    gain, loss = _fit_linear(working)
    rmse = math.sqrt(sum(
        (y - (gain * u + loss * lt)) ** 2 for u, lt, y in working
    ) / len(working))
    return gain, loss, rmse, len(working)


def _robust_equilibrium_fit(
    rows: list[tuple[float, float, float]],
) -> tuple[float, float, float, int]:
    """Constrained fit for closed-loop archives where gain/loss are collinear.

    Quiet hot samples identify the equilibrium ratio ``loss/gain = u/ΔT``.
    The ramp then identifies the remaining gain. This is preferable to accepting
    the negative heat-loss coefficient that unconstrained least squares can
    produce when the controller lowers power as temperature rises.
    """
    equilibrium_ratios = sorted(
        u / (-loss_term)
        for u, loss_term, derivative in rows
        if -loss_term >= 50.0 and 0.01 <= u <= 0.70 and abs(derivative) <= 0.025
    )
    if len(equilibrium_ratios) < 20:
        raise ValueError("not enough quiet hot samples to separate gain and heat loss")
    trim = max(1, len(equilibrium_ratios) // 10)
    ratio = float(median(equilibrium_ratios[trim:-trim] or equilibrium_ratios))
    working = rows
    for _ in range(2):
        transformed = [u + ratio * loss_term for u, loss_term, _y in working]
        denominator = sum(value * value for value in transformed)
        if denominator < 1e-12:
            raise ValueError("insufficient constrained thermal excitation")
        gain = sum(value * row[2] for value, row in zip(
            transformed, working, strict=True)) / denominator
        loss = gain * ratio
        residuals = [
            y - (gain * u + loss * loss_term)
            for u, loss_term, y in working
        ]
        centre = median(residuals)
        mad = median(abs(residual - centre) for residual in residuals)
        cutoff = max(0.02, 4.0 * 1.4826 * mad)
        filtered = [row for row, residual in zip(working, residuals, strict=True)
                    if abs(residual - centre) <= cutoff]
        if len(filtered) < 60 or len(filtered) == len(working):
            break
        working = filtered
    rmse = math.sqrt(sum(
        (y - (gain * u + loss * loss_term)) ** 2
        for u, loss_term, y in working
    ) / len(working))
    return gain, loss, rmse, len(working)


def _rollout_errors(
    trace: ThermalTrace,
    gain: float,
    loss: float,
    lag_sec: float,
) -> list[float]:
    predicted = trace.temperatures_c[0]
    errors: list[float] = []
    for i in range(1, len(trace.times_sec)):
        t0, t1 = trace.times_sec[i - 1], trace.times_sec[i]
        dt = t1 - t0
        if not 0.0 < dt <= 5.0:
            predicted = trace.temperatures_c[i]
            continue
        power = _power_at(trace, (t0 + t1) / 2.0 - lag_sec)
        u = (power / 100.0) ** 2.0
        predicted += dt * (gain * u - loss * (predicted - trace.ambient_c))
        errors.append(predicted - trace.temperatures_c[i])
    return errors


def _fit_best(traces: Sequence[ThermalTrace]) -> tuple[float, float, float, float, int]:
    best: tuple[float, float, float, float, int] | None = None
    for half_seconds in range(31):
        lag = half_seconds / 2.0
        rows = _identification_rows(traces, lag)
        try:
            gain, loss, derivative_rmse, n_samples = _robust_fit(rows)
        except ValueError:
            continue
        if not (0.05 <= gain <= 10.0 and 0.00005 <= loss <= 0.05):
            try:
                gain, loss, derivative_rmse, n_samples = _robust_equilibrium_fit(rows)
            except ValueError:
                continue
        if not (0.05 <= gain <= 10.0 and 0.00005 <= loss <= 0.05):
            continue
        score = derivative_rmse
        if best is None or score < best[2]:
            best = (gain, loss, score, lag, n_samples)
    if best is None:
        raise ValueError("no physically plausible thermal fit")
    return best


def identify_thermal_model(
    traces: Iterable[ThermalTrace],
    *,
    machine_fingerprint: str,
    control_channel: str,
    generated_at: str,
) -> ThermalModelCandidate:
    """Fit a candidate and evaluate it by leave-one-profile-out rollout."""
    qualified = [trace for trace in traces if trace.is_valid()]
    if len(qualified) < 3:
        raise ValueError("at least three qualified preheat profiles are required")
    gain, loss, derivative_rmse, lag, n_samples = _fit_best(qualified)
    rollout_errors = [
        error
        for trace in qualified
        for error in _rollout_errors(trace, gain, loss, lag)
    ]
    rollout_rmse = math.sqrt(sum(e * e for e in rollout_errors) / len(rollout_errors))

    cross_errors: list[float] = []
    for held_out_idx, held_out in enumerate(qualified):
        training = [trace for i, trace in enumerate(qualified) if i != held_out_idx]
        cv_gain, cv_loss, _rmse, cv_lag, _n = _fit_best(training)
        cross_errors.extend(_rollout_errors(held_out, cv_gain, cv_loss, cv_lag))
    cross_rmse = math.sqrt(sum(e * e for e in cross_errors) / len(cross_errors))

    candidate = ThermalModelCandidate(
        machine_fingerprint=machine_fingerprint,
        control_channel=control_channel,
        heating_gain_c_per_sec=gain,
        cooling_coeff_per_sec=loss,
        response_lag_sec=lag,
        derivative_rmse_c_per_sec=derivative_rmse,
        rollout_rmse_c=rollout_rmse,
        cross_validation_rmse_c=cross_rmse,
        n_profiles=len(qualified),
        n_samples=n_samples,
        generated_at=generated_at,
    )
    if not candidate.is_valid():
        raise ValueError("identified model falls outside runtime safety bounds")
    return candidate


@dataclass(frozen=True, slots=True)
class ThermalShadowResult:
    qualified: bool
    passed: bool
    duration_sec: float
    n_samples: int
    rmse_c: float
    bias_c: float
    p95_abs_error_c: float
    reason: str


class ThermalShadowSession:
    """Free-running model observer; it has no actuator or controller callback."""

    def __init__(self, candidate: ThermalModelCandidate) -> None:
        self.candidate = candidate
        self.reset()

    def reset(self) -> None:
        self._predicted_c: float | None = None
        self._first_time: float | None = None
        self._last_time: float | None = None
        self._last_burner = 0.0
        self._commands: deque[tuple[float, float]] = deque()
        self._errors: list[float] = []
        self._temperatures: list[float] = []
        self._burners: list[float] = []
        self._gap_seen = False

    def _delayed_power(self, at_sec: float) -> float:
        value = self._commands[0][1] if self._commands else self._last_burner
        for command_time, command in self._commands:
            if command_time > at_sec:
                break
            value = command
        return value

    def observe(self, *, now: float, temperature_c: float, burner_pct: float,
                ambient_c: float) -> None:
        if not all(math.isfinite(v) for v in (now, temperature_c, burner_pct, ambient_c)):
            self._gap_seen = True
            return
        burner = max(0.0, min(100.0, burner_pct))
        if self._predicted_c is None:
            self._predicted_c = temperature_c
            self._first_time = now
            self._last_time = now
            self._last_burner = burner
            self._commands.append((now, burner))
            self._temperatures.append(temperature_c)
            self._burners.append(burner)
            return
        assert self._last_time is not None
        dt = now - self._last_time
        if not 0.0 < dt <= 5.0:
            self._gap_seen = True
            self._last_time = now
            self._last_burner = burner
            self._commands.append((now, burner))
            return
        lagged = self._delayed_power((self._last_time + now) / 2.0
                                     - self.candidate.response_lag_sec)
        u = (lagged / 100.0) ** self.candidate.heater_exponent
        self._predicted_c += dt * (
            self.candidate.heating_gain_c_per_sec * u
            - self.candidate.cooling_coeff_per_sec * (self._predicted_c - ambient_c)
        )
        self._errors.append(self._predicted_c - temperature_c)
        self._temperatures.append(temperature_c)
        self._burners.append(burner)
        self._last_time = now
        self._last_burner = burner
        self._commands.append((now, burner))
        cutoff = now - self.candidate.response_lag_sec - 2.0
        while len(self._commands) > 2 and self._commands[1][0] < cutoff:
            self._commands.popleft()

    def finish(
        self,
        *,
        min_duration_sec: float = 180.0,
        min_samples: int = 120,
        max_rmse_c: float = 8.0,
        max_bias_c: float = 4.0,
        max_p95_c: float = 12.0,
    ) -> ThermalShadowResult:
        duration = (
            self._last_time - self._first_time
            if self._last_time is not None and self._first_time is not None else 0.0
        )
        n = len(self._errors)
        excitation = (
            bool(self._temperatures)
            and max(self._temperatures) - min(self._temperatures) >= 20.0
            and bool(self._burners)
            and max(self._burners) - min(self._burners) >= 15.0
        )
        qualified = (
            not self._gap_seen
            and duration >= min_duration_sec
            and n >= min_samples
            and excitation
        )
        if not self._errors:
            return ThermalShadowResult(False, False, duration, n, math.inf, math.inf,
                                       math.inf, "no_predictions")
        rmse = math.sqrt(sum(e * e for e in self._errors) / n)
        bias = sum(self._errors) / n
        ordered = sorted(abs(e) for e in self._errors)
        p95 = ordered[min(len(ordered) - 1, math.ceil(0.95 * len(ordered)) - 1)]
        passed = qualified and rmse <= max_rmse_c and abs(bias) <= max_bias_c and p95 <= max_p95_c
        if not qualified:
            reason = "sampling_gap" if self._gap_seen else "insufficient_excitation"
        elif passed:
            reason = "passed"
        else:
            reason = "prediction_error"
        return ThermalShadowResult(qualified, passed, duration, n, rmse, bias, p95, reason)


@dataclass(frozen=True, slots=True)
class ThermalPromotionState:
    """Persistent promotion counters for one immutable candidate fingerprint."""

    consecutive_passes: int = 0
    qualified_sessions: int = 0
    failed_sessions: int = 0
    active: bool = False

    def advance(self, result: ThermalShadowResult, required_passes: int = 3) -> ThermalPromotionState:
        if not result.qualified:
            return self
        passes = self.consecutive_passes + 1 if result.passed else 0
        return ThermalPromotionState(
            consecutive_passes=passes,
            qualified_sessions=self.qualified_sessions + 1,
            failed_sessions=self.failed_sessions + (0 if result.passed else 1),
            # A qualified regression immediately withdraws the prior. The existing
            # learned/default PID remains available and three new passes are required.
            active=passes >= required_passes,
        )
